if [[ "${OSTYPE#*darwin}" != "$OSTYPE" ]] ; then
   
if  `which multitail | /usr/bin/grep -q multitail`  ; then
   alias tailf="mulititail"
   alias tlog="multitail /var/log/system.log"
else
   alias tailf="tail -f"
   alias tlog="tail -f /var/log/system.log"
fi

if [ -f /opt/homebrew/bin/src-hilite-lesspipe.sh ]; then
   export LESSOPEN="| /opt/homebrew/bin/src-hilite-lesspipe.sh %s"
   export LESS=' -R '
fi








fi
